"use client";

import { useMemo, useState } from "react";
import { ArrowLeft, Download, FileUp, UploadCloud } from "lucide-react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";
import { csvValue, parseCsv, type CsvRow } from "@/lib/import/csv";

type Branch = { branch_id: string; branch_name: string; is_headquarters: boolean };
type ImportRow = { name: string; sku?: string; barcode?: string; sale_price?: string; cost_price?: string; stock_quantity?: string; minimum_stock?: string; category?: string; unit?: string; description?: string };
type Field=keyof ImportRow;
const labels:Record<Field,string>={name:"Nome",sku:"SKU",barcode:"Código de barras",sale_price:"Preço de venda",cost_price:"Preço de custo",stock_quantity:"Estoque",minimum_stock:"Estoque mínimo",category:"Categoria",unit:"Unidade",description:"Descrição"};
const aliases = {
  name: ["nome","name","produto","product","item","nome produto","nome do produto","descricao produto","descrição produto"], sku: ["sku","codigo","código","codigo interno","código interno","cod produto","cod. produto","referencia","referência","ref"], barcode: ["barcode","ean","ean13","ean-13","gtin","gtin13","codigo de barras","código de barras","cod barras","cod. barras"], sale_price: ["preco","preço","preco de venda","preço de venda","sale_price","price","valor venda","valor de venda","preco venda","vl venda","valor unitario","valor unitário"], cost_price: ["custo","preco de custo","preço de custo","cost_price","valor custo","valor de custo","custo unitario","custo unitário","preco compra","preço compra"], stock_quantity: ["estoque","stock","quantidade","stock_quantity","qtd","qtde","saldo","saldo estoque","estoque atual","qtd estoque","quantidade estoque"], minimum_stock:["estoque minimo","estoque mínimo","minimum_stock","minimo","mínimo","estoque de seguranca","estoque de segurança","ponto reposicao","ponto de reposicao"], category: ["categoria","category","grupo","departamento","secao","seção"], unit: ["unidade","unit","un","medida","unidade medida"], description: ["descricao","descrição","description","detalhes","observacao","observação"],
} as const;
const decimal = (value: string) => { const normalized = value.trim(); return Number(normalized.includes(",") ? normalized.replace(/\./g, "").replace(",", ".") : normalized); };

export default function ProductImportPage() {
  const supabase = createClient();
  const [rows, setRows] = useState<CsvRow[]>([]);
  const [mapped, setMapped] = useState<ImportRow[]>([]);
  const [fileName, setFileName] = useState("");
  const [branches, setBranches] = useState<Branch[]>([]);
  const [branchId, setBranchId] = useState("");
  const [mode, setMode] = useState<"products" | "prices">("products");
  const [updateExisting, setUpdateExisting] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [mapping,setMapping]=useState<Partial<Record<Field,string>>>({});
  const headers=rows[0]?Object.keys(rows[0]):[];
  const prepareWith=(input:CsvRow[],map:Partial<Record<Field,string>>)=>input.map(row=>Object.fromEntries((Object.keys(labels) as Field[]).map(field=>[field,map[field]?row[map[field]!]??"":csvValue(row,[...aliases[field]])])) as ImportRow);
  const detectMapping=(input:CsvRow[])=>{if(!input[0])return {};const keys=Object.keys(input[0]);const result:Partial<Record<Field,string>>={};(Object.keys(labels) as Field[]).forEach(field=>{const normalized=aliases[field].map(x=>x.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase());const found=keys.find(k=>normalized.includes(k.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()));if(found)result[field]=found;});return result;};

  const prepare = (input: CsvRow[]) => prepareWith(input,detectMapping(input));
  const validation = useMemo(() => { const seen = new Set<string>(); return mapped.map((row, index) => { const errors: string[] = []; if (mode === "products" && !row.name?.trim()) errors.push("nome obrigatório"); if (!row.sku?.trim() && !row.barcode?.trim()) errors.push("SKU ou código de barras obrigatório"); const identity = (row.barcode || row.sku || "").trim().toLowerCase(); if (identity && seen.has(identity)) errors.push("duplicado no arquivo"); if (identity) seen.add(identity); for (const field of ["sale_price", "cost_price", "stock_quantity","minimum_stock"] as const) { if (row[field] && (!Number.isFinite(decimal(row[field])) || decimal(row[field]) < 0)) errors.push(`${field} inválido`); } return { index, errors }; }); }, [mapped, mode]);
  const validRows = useMemo(() => mapped.filter((_, index) => !validation[index]?.errors.length), [mapped, validation]);

  async function loadBranches() { const { data } = await supabase.rpc("get_my_branches"); const next = (data ?? []) as Branch[]; setBranches(next); if (!branchId && next[0]) setBranchId(next[0].branch_id); }
  async function onFile(file?: File) { if (!file) return; setError(""); if (!file.name.toLowerCase().endsWith(".csv")) { setError("Envie um arquivo CSV."); return; } const parsed = parseCsv(await file.text()); const detected=detectMapping(parsed); setFileName(file.name); setRows(parsed); setMapping(detected); setMapped(prepareWith(parsed,detected)); await loadBranches(); }
  async function submit() { if (!branchId) { setError("Selecione a filial que receberá o estoque importado."); return; } if (!validRows.length) { setError("Corrija as linhas inválidas antes de importar."); return; } setBusy(true); setError(""); setMessage(""); const payload = validRows.map((row) => Object.fromEntries(Object.entries(row).filter(([, value]) => value !== "").map(([key, value]) => [key, ["sale_price", "cost_price", "stock_quantity","minimum_stock"].includes(key) ? decimal(value as string) : value]))); const { data, error: rpcError } = await supabase.rpc("import_products_batch", { p_branch_id: branchId, p_rows: payload, p_mode: mode, p_update_existing: updateExisting, p_file_name: fileName }); if (rpcError) setError(rpcError.message); else { const result = data as { inserted: number; updated: number; skipped: number; errors: Array<{ line: number; message: string }> }; setMessage(`${result.inserted} inserido(s), ${result.updated} atualizado(s), ${result.skipped} ignorado(s). ${result.errors.length} linha(s) com erro.`); } setBusy(false); }
  function downloadModel() { const content = "nome;sku;barcode;preco_venda;preco_custo;estoque;categoria;unidade;descricao\nCafé 500g;CAF-001;7890000000000;18,90;12,00;10;Mercearia;UN;Produto de exemplo\n"; const url = URL.createObjectURL(new Blob(["\uFEFF" + content], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "modelo-produtos-meucaixa.csv"; anchor.click(); URL.revokeObjectURL(url); }

  return <div className="page"><div className="page-header"><div><Link className="report-link" href="/dashboard/produtos"><ArrowLeft size={15} /> Produtos</Link><span className="eyebrow">CATÁLOGO</span><h1>Importar produtos</h1><p>Importe produtos ou atualize preços em lote. O estoque é lançado na filial escolhida com histórico operacional.</p></div><button className="button secondary" onClick={downloadModel}><Download size={15} /> Baixar modelo CSV</button></div>
    {error && <div className="error">{error}</div>}{message && <div className="success">{message}</div>}
    <div className="panel"><h2><UploadCloud size={19} /> 1. Escolha o arquivo</h2><p>O MeuCaixa identifica automaticamente vírgula ou ponto e vírgula e tenta reconhecer as colunas independentemente da ordem ou do nome usado pelo outro sistema.</p><label className="button secondary"><FileUp size={15} /> Selecionar CSV<input hidden type="file" accept=".csv,text/csv" onChange={(e) => void onFile(e.target.files?.[0])} /></label>{fileName && <p><strong>{fileName}</strong> · {rows.length} linha(s) encontrada(s)</p>}</div>
    {mapped.length > 0 && <><div className="panel"><h2>2. Colunas reconhecidas</h2><p>Confira o que o MeuCaixa entendeu. Se alguma coluna veio com outro nome, basta escolher manualmente antes de importar.</p><div className="form-grid">{(Object.keys(labels) as Field[]).map(field=><label key={field}>{labels[field]}<select className="field" value={mapping[field]??""} onChange={e=>{const next={...mapping,[field]:e.target.value||undefined};setMapping(next);setMapped(prepareWith(rows,next));}}><option value="">Não importar</option>{headers.map(h=><option key={h} value={h}>{h}</option>)}</select></label>)}</div></div><div className="panel"><h2>3. Regras da importação</h2><div className="form-grid"><label>Filial do estoque<select className="field" value={branchId} onChange={(e) => setBranchId(e.target.value)}>{branches.map((branch) => <option key={branch.branch_id} value={branch.branch_id}>{branch.is_headquarters ? "Matriz · " : ""}{branch.branch_name}</option>)}</select></label><label>Modo<select className="field" value={mode} onChange={(e) => setMode(e.target.value as "products" | "prices")}><option value="products">Produtos completos</option><option value="prices">Somente preços</option></select></label><label className="report-check"><input type="checkbox" checked={updateExisting} onChange={(e) => setUpdateExisting(e.target.checked)} /> Atualizar produtos existentes</label></div><p>{mode === "prices" ? "Use SKU ou código de barras + preço de venda. Estoque, nome e custo serão preservados." : "Produtos existentes são ignorados por padrão; marque atualizar para alterar cadastro e preço."}</p></div><div className="panel"><h2>4. Revisão</h2><p>{validRows.length} linha(s) pronta(s) · {validation.filter((item) => item.errors.length).length} com erro</p><div className="report-table-wrap"><table className="report-table"><thead><tr><th>Linha</th><th>Nome</th><th>SKU / EAN</th><th>Preço</th><th>Estoque</th><th>Validação</th></tr></thead><tbody>{mapped.slice(0, 100).map((row, index) => <tr key={index}><td>{index + 2}</td><td>{row.name || "—"}</td><td>{row.sku || row.barcode || "—"}</td><td>{row.sale_price || "—"}</td><td>{row.stock_quantity || "—"}</td><td>{validation[index]?.errors.length ? validation[index].errors.join(", ") : "OK"}</td></tr>)}</tbody></table></div><button className="button primary" onClick={() => void submit()} disabled={busy || !validRows.length}>{busy ? "Importando..." : `Importar ${validRows.length} linha(s)`}</button></div></>}
  </div>;
}
