'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import PasswordField from '@/components/PasswordField';

export default function ResetPasswordPage() {
  const [ready, setReady] = useState(false); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  useEffect(() => { const supabase = createClient(); const recoveryFlow = new URLSearchParams(window.location.search).get('flow') === 'recovery'; const { data } = supabase.auth.onAuthStateChange((event, session) => { if (event === 'PASSWORD_RECOVERY' || (recoveryFlow && session)) setReady(true); }); supabase.auth.getSession().then(({ data: sessionData }) => { if (recoveryFlow && sessionData.session) setReady(true); }); return () => data.subscription.unsubscribe(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); if (password.length < 8) { setError('A senha precisa ter pelo menos 8 caracteres.'); return; } if (password !== confirm) { setError('As senhas não coincidem.'); return; } setLoading(true); const { error: updateError } = await createClient().auth.updateUser({ password }); if (updateError) setError(updateError.message); else setMessage('Senha alterada com sucesso.'); setLoading(false); }
  return <main className="login-page"><section className="login-card"><div className="kumo-login-brand"><img className="kumo-logo" src="/kumo-logo.svg" alt="Kumo — Soluções em Tecnologia" /></div><span className="eyebrow">MEUCAIXA</span><h1>Definir nova senha</h1><p>Escolha uma nova senha para sua conta.</p>{!ready && !message && <div className="error">O link é inválido ou expirou. Solicite um novo link.</div>}<form onSubmit={submit} className="login-form"><PasswordField label="Nova senha" value={password} onChange={event => setPassword(event.target.value)} autoComplete="new-password" minLength={8} required /><PasswordField label="Confirmar senha" value={confirm} confirmValue={password} onChange={event => setConfirm(event.target.value)} autoComplete="new-password" minLength={8} required />{error && <div className="error">{error}</div>}{message && <div className="success">{message}</div>}<button className="button primary login-button" disabled={loading || !ready}>{loading ? 'Salvando...' : 'Salvar nova senha'}</button></form>{message && <div className="login-links"><Link href="/login">Voltar para o login</Link></div>}</section></main>;
}
