"use client";

import {useEffect,useMemo,useState} from "react";
import {Banknote,Barcode,Check,ChevronDown,CreditCard,Minus,Plus,Receipt,Search,ShoppingCart,Smartphone,Trash2,UserRound,X} from "lucide-react";

type Product={id:string;name:string;category:string;price:number;stock:number;barcode:string};
type CartItem=Product&{quantity:number};
type PaymentMethod="pix"|"cash"|"debit"|"credit";
type Sale={id:string;createdAt:string;items:CartItem[];subtotal:number;discount:number;total:number;payment:PaymentMethod;received:number;change:number;customer:string};

const DEMO_PRODUCTS:Product[]=[
{id:"1",name:"Arroz 5kg",category:"Mercearia",price:29.9,stock:24,barcode:"7891000100011"},{id:"2",name:"Feijão carioca 1kg",category:"Mercearia",price:8.49,stock:31,barcode:"7891000100028"},{id:"3",name:"Óleo de soja 900ml",category:"Mercearia",price:7.99,stock:18,barcode:"7891000100035"},{id:"4",name:"Leite integral 1L",category:"Laticínios",price:5.79,stock:42,barcode:"7891000100042"},{id:"5",name:"Café torrado 500g",category:"Mercearia",price:18.9,stock:15,barcode:"7891000100059"},{id:"6",name:"Açúcar 1kg",category:"Mercearia",price:4.99,stock:27,barcode:"7891000100066"},{id:"7",name:"Refrigerante cola 2L",category:"Bebidas",price:9.49,stock:20,barcode:"7891000100073"},{id:"8",name:"Água mineral 500ml",category:"Bebidas",price:2.5,stock:60,barcode:"7891000100080"},{id:"9",name:"Pão de forma",category:"Padaria",price:8.9,stock:12,barcode:"7891000100097"},{id:"10",name:"Queijo muçarela 500g",category:"Laticínios",price:24.9,stock:9,barcode:"7891000100103"},{id:"11",name:"Detergente 500ml",category:"Limpeza",price:2.99,stock:36,barcode:"7891000100110"},{id:"12",name:"Papel higiênico 12un",category:"Higiene",price:17.9,stock:16,barcode:"7891000100127"}];

const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const paymentLabel:Record<PaymentMethod,string>={pix:"PIX",cash:"Dinheiro",debit:"Débito",credit:"Crédito"};

export default function VendasPage(){
 const[products,setProducts]=useState<Product[]>(DEMO_PRODUCTS),[cart,setCart]=useState<CartItem[]>([]),[query,setQuery]=useState(""),[category,setCategory]=useState("Todos"),[payment,setPayment]=useState<PaymentMethod>("pix"),[discount,setDiscount]=useState(""),[received,setReceived]=useState(""),[customer,setCustomer]=useState(""),[showCheckout,setShowCheckout]=useState(false),[showReceipt,setShowReceipt]=useState(false),[lastSale,setLastSale]=useState<Sale|null>(null),[barcodeInput,setBarcodeInput]=useState(""),[message,setMessage]=useState("");

 useEffect(()=>{try{const p=localStorage.getItem("meucaixa-products");if(p)setProducts(JSON.parse(p));if(!localStorage.getItem("meucaixa-sales"))localStorage.setItem("meucaixa-sales","[]")}catch{}},[]);\n useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key==="F2"){e.preventDefault();document.querySelector<HTMLInputElement>(".pos-search input")?.focus()}if(e.key==="F4"){e.preventDefault();if(cart.length)setShowCheckout(true)}if(e.key==="Escape"){setQuery("");setBarcodeInput("");if(showCheckout)setShowCheckout(false);if(showReceipt)setShowReceipt(false)}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[cart.length,showCheckout,showReceipt]);
 const categories=useMemo(()=>["Todos",...Array.from(new Set(products.map(p=>p.category)))],[products]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return products.filter(p=>(category==="Todos"||p.category===category)&&(!q||p.name.toLowerCase().includes(q)||p.barcode.includes(q)))},[products,query,category]);
 const subtotal=useMemo(()=>cart.reduce((s,i)=>s+i.price*i.quantity,0),[cart]),discountValue=Math.min(Math.max(Number(discount)||0,0),subtotal),total=Math.max(subtotal-discountValue,0),receivedValue=Number(received)||0,change=Math.max(receivedValue-total,0),canFinish=cart.length>0&&(payment!=="cash"||receivedValue>=total);

 const add=(p:Product)=>{if(p.stock<=0)return;setCart(c=>{const e=c.find(i=>i.id===p.id);return e?c.map(i=>i.id===p.id?{...i,quantity:Math.min(i.quantity+1,p.stock)}:i):[...c,{...p,quantity:1}]});setMessage("")};
 const barcode=()=>{const p=products.find(i=>i.barcode===barcodeInput.trim());if(!p){setMessage("Produto não encontrado para este código.");return}add(p);setBarcodeInput("")};
 const qty=(id:string,d:number)=>setCart(c=>c.map(i=>i.id===id?{...i,quantity:Math.min(Math.max(i.quantity+d,0),i.stock)}:i).filter(i=>i.quantity>0));
 const finish=()=>{if(!canFinish){setMessage(payment==="cash"?"Informe um valor recebido suficiente para a venda.":"Revise os dados da venda.");return}const sale:Sale={id:"MC-"+Date.now().toString().slice(-8),createdAt:new Date().toISOString(),items:cart,subtotal,discount:discountValue,total,payment,received:payment==="cash"?receivedValue:total,change:payment==="cash"?change:0,customer:customer.trim()||"Consumidor"};try{const old:Sale[]=JSON.parse(localStorage.getItem("meucaixa-sales")||"[]");localStorage.setItem("meucaixa-sales",JSON.stringify([sale,...old].slice(0,200)));const updated=products.map(p=>{const i=cart.find(c=>c.id===p.id);return i?{...p,stock:Math.max(p.stock-i.quantity,0)}:p});localStorage.setItem("meucaixa-products",JSON.stringify(updated));setProducts(updated)}catch{}setLastSale(sale);setCart([]);setDiscount("");setReceived("");setCustomer("");setShowCheckout(false);setShowReceipt(true);setMessage("")};

 return <div className="page pos-page">
  <div className="pos-topbar"><div><span className="eyebrow">PONTO DE VENDA</span><h1>Nova venda</h1><p>Atenda seu cliente sem sair da tela do caixa.</p></div><div className="pos-top-actions"><a className="button secondary" href="/dashboard/vendas/historico"><Receipt size={17}/> Histórico</a><span className="cash-status"><span/> Caixa em operação</span></div></div>
  <div className="pos-layout"><section className="pos-catalog">
   <div className="pos-search-row"><div className="pos-search"><Search size={19}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produto por nome..."/><kbd>F2</kbd></div><div className="barcode-search"><Barcode size={19}/><input value={barcodeInput} onChange={e=>setBarcodeInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&barcode()} placeholder="Código de barras"/><button onClick={barcode}>Adicionar</button></div></div>
   <div className="category-strip">{categories.map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div>
   <div className="catalog-heading"><div><strong>Produtos</strong><span>{filtered.length} itens</span></div><button className="text-button" onClick={()=>{setQuery("");setCategory("Todos")}}>Limpar filtros</button></div>
   <div className="pos-product-grid">{filtered.map(p=><button key={p.id} className="pos-product" disabled={p.stock<=0} onClick={()=>add(p)}><span className="product-icon">{p.name[0]}</span><span className="product-info"><strong>{p.name}</strong><small>{p.category}</small></span><span className="product-price">{money(p.price)}</span><span className={p.stock<=5?"stock warning":"stock"}>{p.stock} un.</span></button>)}</div>
   {message&&<div className="error pos-message">{message}</div>}<div className="pos-shortcuts"><span><kbd>F2</kbd> buscar</span><span><kbd>F4</kbd> pagamento</span><span><kbd>Esc</kbd> limpar busca</span></div>
  </section>
  <aside className="pos-cart"><div className="cart-header"><div><span className="eyebrow">VENDA ATUAL</span><h2>Carrinho <span>{cart.reduce((s,i)=>s+i.quantity,0)}</span></h2></div>{cart.length>0&&<button className="icon-button danger" onClick={()=>setCart([])}><Trash2 size={17}/></button>}</div>
   <div className="customer-field"><UserRound size={17}/><input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Consumidor / cliente"/><ChevronDown size={15}/></div>
   <div className="cart-items">{cart.map(i=><div className="pos-cart-item" key={i.id}><div className="cart-item-main"><strong>{i.name}</strong><small>{money(i.price)} cada</small></div><div className="quantity-control"><button onClick={()=>qty(i.id,-1)}><Minus size={13}/></button><strong>{i.quantity}</strong><button onClick={()=>qty(i.id,1)}><Plus size={13}/></button></div><strong className="line-total">{money(i.price*i.quantity)}</strong><button className="remove-item" onClick={()=>setCart(c=>c.filter(x=>x.id!==i.id))}><X size={14}/></button></div>)}{!cart.length&&<div className="empty-cart"><ShoppingCart size={38}/><strong>Seu carrinho está vazio</strong><span>Toque em um produto para começar a venda.</span></div>}</div>
   <div className="cart-summary"><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div className="discount-line"><span>Desconto</span><label>R$ <input type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)} placeholder="0,00"/></label></div><div className="grand-total"><span>Total</span><strong>{money(total)}</strong></div></div>
   <button className="button primary checkout-button" disabled={!cart.length} onClick={()=>setShowCheckout(true)}><CreditCard size={18}/> Ir para pagamento</button>
  </aside></div>
  {showCheckout&&<div className="modal-backdrop" onMouseDown={()=>setShowCheckout(false)}><div className="checkout-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div><span className="eyebrow">FINALIZAR VENDA</span><h2>Como o cliente vai pagar?</h2></div><button className="icon-button" onClick={()=>setShowCheckout(false)}><X size={18}/></button></div><div className="checkout-total">{money(total)}</div>
   <div className="payment-grid">{([["pix",Smartphone,"PIX","Pagamento instantâneo"],["cash",Banknote,"Dinheiro","Calcular troco"],["debit",CreditCard,"Débito","Cartão de débito"],["credit",CreditCard,"Crédito","Cartão de crédito"]] as const).map(([key,Icon,title,sub])=><button key={key} className={payment===key?"payment-option active":"payment-option"} onClick={()=>setPayment(key)}><Icon size={22}/><strong>{title}</strong><small>{sub}</small></button>)}</div>
   {payment==="cash"&&<div className="cash-received"><label>Valor recebido<input className="field large-field" autoFocus type="number" min="0" step="0.01" value={received} onChange={e=>setReceived(e.target.value)} placeholder="0,00"/></label><div className={receivedValue>=total?"change-box":"change-box pending"}><span>{receivedValue>=total?"Troco":"Falta receber"}</span><strong>{money(receivedValue>=total?change:total-receivedValue)}</strong></div></div>}
   <div className="checkout-footer"><div><small>{cart.length} produto(s)</small><strong>{money(total)}</strong></div><button className="button primary finish-button" onClick={finish} disabled={!canFinish}><Check size={18}/> Confirmar venda</button></div>
  </div></div>}
  {showReceipt&&lastSale&&<div className="modal-backdrop" onMouseDown={()=>setShowReceipt(false)}><div className="receipt-modal" onMouseDown={e=>e.stopPropagation()}><div className="receipt-success"><Check size={30}/></div><span className="eyebrow">VENDA CONCLUÍDA</span><h2>{lastSale.id}</h2><p>Venda registrada com sucesso em modo demonstração.</p><div className="receipt-box"><div><span>Pagamento</span><strong>{paymentLabel[lastSale.payment]}</strong></div><div><span>Total</span><strong>{money(lastSale.total)}</strong></div>{lastSale.payment==="cash"&&<div><span>Troco</span><strong>{money(lastSale.change)}</strong></div>}</div><div className="receipt-actions"><button className="button secondary" onClick={()=>setShowReceipt(false)}>Nova venda</button><button className="button primary" onClick={()=>window.print()}><Receipt size={17}/> Imprimir</button></div></div></div>}
 </div>;
}