"use client";
import { useEffect,useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Product={id:string;name:string;sale_price:number;stock_quantity:number;unit:string;barcode:string|null};
type Cart={product:Product;quantity:number};
export default function VendasPage(){
 const supabase=createClient();const [products,setProducts]=useState<Product[]>([]);const [cart,setCart]=useState<Cart[]>([]);const [query,setQuery]=useState("");const [method,setMethod]=useState("pix");const [msg,setMsg]=useState("");const [loading,setLoading]=useState(false);
 useEffect(()=>{supabase.from("products").select("id,name,sale_price,stock_quantity,unit,barcode").eq("active",true).order("name").then(({data})=>setProducts((data??[]) as Product[]))},[]);
 const filtered=products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())||(p.barcode??"").includes(query)).slice(0,12);
 const total=useMemo(()=>cart.reduce((n,i)=>n+Number(i.product.sale_price)*i.quantity,0),[cart]);
 function add(p:Product){setCart(c=>{const found=c.find(i=>i.product.id===p.id);if(found)return c.map(i=>i.product.id===p.id?{...i,quantity:Math.min(i.quantity+1,Number(p.stock_quantity))}:i);return [...c,{product:p,quantity:1}]})}
 async function finish(){if(!cart.length)return;setLoading(true);setMsg("");const {data:org}=await supabase.rpc("get_my_organization");const branch=org?.[0]?.branch_id;if(!branch){setMsg("Configure a unidade primeiro.");setLoading(false);return}const {error}=await supabase.rpc("complete_sale",{p_branch_id:branch,p_items:cart.map(i=>({product_id:i.product.id,quantity:i.quantity})),p_payments:[{method,amount:total}],p_discount:0});if(error)setMsg(error.message);else{setMsg("Venda concluída com sucesso.");setCart([]);const {data}=await supabase.from("products").select("id,name,sale_price,stock_quantity,unit,barcode").eq("active",true).order("name");setProducts((data??[]) as Product[])}setLoading(false)}
 return <div className="page"><div className="page-header"><div><span className="eyebrow">PONTO DE VENDA</span><h1>Vendas</h1><p>Selecione produtos, monte o carrinho e finalize a venda.</p></div></div>
 <div className="pos-grid"><div className="panel"><input className="field search-field" placeholder="Buscar produto ou código de barras" value={query} onChange={e=>setQuery(e.target.value)} /><div className="product-grid">{filtered.map(p=><button className="product-card" key={p.id} onClick={()=>add(p)} disabled={Number(p.stock_quantity)<=0}><strong>{p.name}</strong><span>R$ {Number(p.sale_price).toFixed(2).replace(".",",")}</span><small>Estoque: {p.stock_quantity}</small></button>)}</div></div>
 <div className="panel cart-panel"><h2>Carrinho</h2>{cart.map(i=><div className="cart-line" key={i.product.id}><span>{i.product.name} × {i.quantity}</span><strong>R$ {(Number(i.product.sale_price)*i.quantity).toFixed(2).replace(".",",")}</strong></div>)}{!cart.length&&<p>Nenhum produto selecionado.</p>}<div className="cart-total"><span>Total</span><strong>R$ {total.toFixed(2).replace(".",",")}</strong></div><select className="field" value={method} onChange={e=>setMethod(e.target.value)}><option value="pix">PIX</option><option value="cash">Dinheiro</option><option value="debit_card">Cartão de débito</option><option value="credit_card">Cartão de crédito</option></select><button className="button primary checkout" disabled={!cart.length||loading} onClick={finish}>{loading?"Finalizando...":"Finalizar venda"}</button>{msg&&<div className={msg.startsWith("Venda")?"success":"error"}>{msg}</div>}</div></div>
 </div>;
}