"use client";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
const money=(v:number)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default function CaixaPage(){
 const s=createClient(); const[org,setOrg]=useState<any>(null); const[summary,setSummary]=useState<any>(null); const[operators,setOperators]=useState<any[]>([]); const[operator,setOperator]=useState(""); const[opening,setOpening]=useState("0"); const[msg,setMsg]=useState(""); const[loading,setLoading]=useState(false);
 async function load(){const{data}=await s.rpc("get_my_organization");if(!data?.[0])return;setOrg(data[0]);const current=await s.rpc("get_cash_current_summary",{p_branch_id:data[0].branch_id});setSummary(current.data?.[0]??null);const members=await s.from("organization_members").select("user_id,role,profiles(full_name)").eq("organization_id",data[0].organization_id).eq("active",true);setOperators(members.data??[])}
 useEffect(()=>{void load()},[]);
 async function open(){setLoading(true);setMsg("");const{error}=await s.rpc("open_cash_register",{p_branch_id:org.branch_id,p_opening_balance:Number(opening)||0,p_operator_user_id:operator||null});if(error)setMsg(error.message);else await load();setLoading(false)}
 return <div className="page"><div className="page-header"><div><span className="eyebrow">OPERAÇÃO</span><h1>Caixa</h1><p>Abra, acompanhe e feche o caixa da sua unidade.</p></div></div>{!summary?<div className="panel"><h2>Abrir caixa</h2><p>Informe o dinheiro disponível no início do expediente.</p>{operators.length>1&&<label>Operador<select className="field" value={operator} onChange={e=>setOperator(e.target.value)}><option value="">Eu mesmo</option>{operators.map(x=><option key={x.user_id} value={x.user_id}>{x.profiles?.full_name||x.role}</option>)}</select></label>}<div className="inline-form"><input className="field" type="number" min="0" step=".01" value={opening} onChange={e=>setOpening(e.target.value)} placeholder="Saldo inicial"/><button className="button primary" onClick={open} disabled={loading}>{loading?"Abrindo...":"Abrir caixa"}</button></div>{msg&&<div className="error">{msg}</div>}</div>:<><div className="stats-row"><div className="stat-card"><small>Status</small><strong>Aberto</strong></div><div className="stat-card"><small>Vendas</small><strong>{money(summary.cash_sales)}</strong></div><div className="stat-card"><small>Entradas</small><strong>{money(summary.cash_entries)}</strong></div><div className="stat-card"><small>Saldo esperado</small><strong>{money(summary.expected_balance)}</strong></div></div><div className="panel"><h2>Caixa atual</h2><p>O caixa está vinculado à unidade <strong>{org?.branch_name}</strong>. As vendas feitas pelo PDV entram automaticamente aqui.</p></div></>}</div>;
}
